name: 🚀 Deploy Varas Consultorio API to Azure VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_KEY }}
        source: "."
        target: "/root/varas_consultorio"

    - name: Run deploy commands on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_KEY }}
        script: |
          set -e
          cd /root/varas_consultorio

          printf "%s" "${{ secrets.ENV_FILE }}" > .env

          npm install
          npm run build

          pm2 stop varas_consultorio-api || true
          pm2 delete varas_consultorio-api || true
          pm2 start dist/main.js --name varas_consultorio-api
          pm2 save